# Generated by Django 5.1 on 2024-09-01 06:37

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_asset_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assetinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('item_id', models.CharField(default='', max_length=20)),
                ('entry_date', models.DateField(default=datetime.datetime.now)),
                ('statusID', models.CharField(max_length=20)),
                ('tag_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.asset')),
            ],
        ),
    ]
