# Generated by Django 5.1 on 2024-09-01 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_assetinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='Id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='asset',
            name='price',
            field=models.CharField(default='', max_length=100),
        ),
    ]
