# Generated by Django 5.1 on 2024-09-01 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_asset_id_asset_purchased_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset',
            options={},
        ),
        migrations.AddField(
            model_name='asset',
            name='Id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('employee_name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='assets.asset')),
            ],
            options={
                'permissions': [('can_add_asset', 'Can add asset'), ('can_delete_asset', 'Can delete asset'), ('can_change_asset', 'Can change asset'), ('can_view_asset', 'Can view asset'), ('can_approve_asset', 'Can approve asset')],
            },
        ),
        migrations.DeleteModel(
            name='Assetinfo',
        ),
    ]
