# Generated by Django 5.1 on 2024-09-01 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0007_alter_asset_options_asset_id_company_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.CharField(default='', max_length=100)),
                ('category_name', models.CharField(choices=[('office', 'Office'), ('lab', 'Lab'), ('classroom', 'Classroom'), ('sports', 'Sports'), ('others', 'Others')], max_length=50)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='assets.asset')),
            ],
        ),
    ]
