# Generated by Django 5.1 on 2024-09-01 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0009_employee_remove_category_asset_managedasset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managedasset',
            name='category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_assets', to='assets.category'),
        ),
    ]
