# Generated by Django 5.1 on 2024-09-01 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0011_alter_managedasset_category_id_assetissue'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
            ],
        ),
    ]
